version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movieapp-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - sqldata:/var/opt/mssqls
    restart: unless-stopped
  adminer:
    image: adminer
    container_name: movieapp-adminer
    restart: unless-stopped
    ports:
      - "4242:8080"

volumes:
  sqldata: 