using System.ComponentModel.DataAnnotations;

namespace MovieApp.Api.Models;

/// <summary>
/// Represents a movie in the system
/// </summary>
public class Movie
{
    /// <summary>
    /// Unique identifier for the movie
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Title of the movie
    /// </summary>
    [Required]
    [StringLength(200)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Description or plot summary of the movie
    /// </summary>
    [Required]
    public string Overview { get; set; } = string.Empty;

    /// <summary>
    /// URL to the movie's poster image
    /// </summary>
    public string? PosterPath { get; set; }

    /// <summary>
    /// Release year of the movie
    /// </summary>
    public DateTime ReleaseDate { get; set; }

    /// <summary>
    /// Average rating of the movie
    /// </summary>
    public double VoteAverage { get; set; }

    /// <summary>
    /// Number of votes for the movie
    /// </summary>
    public int VoteCount { get; set; }

    // New fields for enhanced movie information
    /// <summary>
    /// Language of the movie
    /// </summary>
    public string? OriginalLanguage { get; set; }
    
    /// <summary>
    /// Alternative title of the movie
    /// </summary>
    public string? OriginalTitle { get; set; }
    
    /// <summary>
    /// Whether the movie is local
    /// </summary>
    public bool IsLocal { get; set; }
    
    /// <summary>
    /// Director of the movie
    /// </summary>
    public string? Director { get; set; }
    
    /// <summary>
    /// Main actors in the movie
    /// </summary>
    public string? Cast { get; set; } // Stored as comma-separated string
    
    /// <summary>
    /// Genres of the movie
    /// </summary>
    public string? Genres { get; set; } // Stored as comma-separated string
    
    /// <summary>
    /// Runtime of the movie in minutes
    /// </summary>
    public int? Runtime { get; set; } // Runtime in minutes
    
    /// <summary>
    /// Tagline of the movie
    /// </summary>
    public string? Tagline { get; set; }
    
    /// <summary>
    /// Status of the movie
    /// </summary>
    public string? Status { get; set; } // Released, In Production, etc.
    
    /// <summary>
    /// Budget of the movie
    /// </summary>
    public decimal? Budget { get; set; }
    
    /// <summary>
    /// Revenue generated by the movie
    /// </summary>
    public decimal? Revenue { get; set; }
    
    /// <summary>
    /// Production companies involved in the movie
    /// </summary>
    public string? ProductionCompanies { get; set; } // Stored as comma-separated string
    
    /// <summary>
    /// Production countries involved in the movie
    /// </summary>
    public string? ProductionCountries { get; set; } // Stored as comma-separated string
    
    /// <summary>
    /// Spoken languages in the movie
    /// </summary>
    public string? SpokenLanguages { get; set; } // Stored as comma-separated string
    
    /// <summary>
    /// Keywords associated with the movie
    /// </summary>
    public string? Keywords { get; set; } // Stored as comma-separated string for search
    
    /// <summary>
    /// URL to the movie's trailer
    /// </summary>
    public string? TrailerUrl { get; set; }
    
    /// <summary>
    /// URL to the movie's homepage
    /// </summary>
    public string? Homepage { get; set; }
    
    /// <summary>
    /// Whether the movie is for adult audiences
    /// </summary>
    public bool IsAdult { get; set; }
    
    /// <summary>
    /// Popularity score of the movie
    /// </summary>
    public double? Popularity { get; set; }
    
    // User rating fields
    /// <summary>
    /// Average user rating of the movie
    /// </summary>
    public double? UserRatingAverage { get; set; }
    
    /// <summary>
    /// Number of user ratings for the movie
    /// </summary>
    public int? UserRatingCount { get; set; }
    
    // Metadata
    /// <summary>
    /// Date when the movie was added to the system
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    /// <summary>
    /// ID of the user who added the movie
    /// </summary>
    public int CreatedById { get; set; }
    /// <summary>
    /// User who added the movie
    /// </summary>
    public User CreatedBy { get; set; } = null!;
    /// <summary>
    /// Date when the movie was last updated
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
    /// <summary>
    /// ID of the user who last updated the movie
    /// </summary>
    public int? UpdatedById { get; set; }
    /// <summary>
    /// User who last updated the movie
    /// </summary>
    public User? UpdatedBy { get; set; }
} 